version: '3.8'

services:
  arrow-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: arrow_duckdb_service
    ports:
      - "5000:5000"
    volumes:
      # LEFT side is the server path (colleague changes this). RIGHT side is inside the container (leave this alone).
      - ./data:/app/data
    environment:
      - GEOPARQUET_PATH=/app/data/egms_optimized_be.geoparquet
    restart: unless-stopped