# generate_hybrid_geoparquet_final_duckdb.py (CRITICAL FIX APPLIED)
import duckdb
import os
import shutil

# --- Configuration ---
INPUT_WIDE_CSV_PATH = '/Users/marianakecova/GST/3DFLUS_CCN/UC5_PRAHA_EGMS/t146/SRC_DATA/EGMS_L2b_146_0296_IW2_VV_2019_2023_1.csv'
OUTPUT_TILED_GEOPARQUET_DIR = '/Users/marianakecova/GST/3DFLUS_CCN/UC5_PRAHA_EGMS/t146/SRC_DATA/egms_tiled_detail_v2'
GRID_SIZE = 0.10

STATIC_COLUMNS = [
    'pid', 'mp_type', 'latitude', 'longitude', 'easting', 'northing', 'height',
    'height_wgs84', 'line', 'pixel', 'rmse', 'temporal_coherence',
    'amplitude_dispersion', 'incidence_angle', 'track_angle', 'los_east',
    'los_north', 'los_up', 'mean_velocity', 'mean_velocity_std',
    'acceleration', 'acceleration_std', 'seasonality', 'seasonality_std'
]
# --- End Configuration ---

print(f"--- Starting FINAL DUCKDB COPY Generation ---")

con = duckdb.connect()
con.install_extension('spatial')
con.load_extension('spatial')
con.install_extension('httpfs')
con.load_extension('httpfs')

# Clean output directory before starting
if os.path.exists(OUTPUT_TILED_GEOPARQUET_DIR):
    shutil.rmtree(OUTPUT_TILED_GEOPARQUET_DIR)
os.makedirs(OUTPUT_TILED_GEOPARQUET_DIR)

try:
    static_cols_str = ", ".join([f'"{col}"' for col in STATIC_COLUMNS])

    # 1. Define the main transformation SQL (no trailing semicolon!)
    transformation_sql = f"""
    WITH UnpivotedData AS (
        UNPIVOT read_csv_auto('{INPUT_WIDE_CSV_PATH}')
        ON COLUMNS(* EXCLUDE ({static_cols_str}))
        INTO NAME date_str VALUE displacement
    ),
    HybridData AS (
        SELECT
            {static_cols_str},
            LIST(STRPTIME(date_str, '%Y%m%d')::DATE) AS dates,
            LIST(displacement) AS displacements
        FROM UnpivotedData
        GROUP BY {static_cols_str}
    )
    SELECT
        * EXCLUDE (latitude, longitude),

        -- Geometry and Metadata Columns
        ST_GeomFromWKB(ST_AsWKB(ST_Point(longitude, latitude))) AS geom_wkb,
        'X' || FLOOR(longitude / {GRID_SIZE}) AS part_x,
        'Y' || FLOOR(latitude / {GRID_SIZE}) AS part_y,
        longitude AS bbox_xmin,
        latitude AS bbox_ymin,
        longitude AS bbox_xmax,
        latitude AS bbox_ymax

    FROM HybridData
    """ # 🛑 NO SEMICOLON HERE 🛑

    # 2. Use the DuckDB COPY command to write the result as a partitioned dataset
    # The COPY command requires the entire SELECT/WITH query inside parentheses (the subquery).
    copy_sql = f"""
    COPY ({transformation_sql}) TO '{OUTPUT_TILED_GEOPARQUET_DIR}' (
        FORMAT PARQUET,
        PARTITION_BY (part_x, part_y),
        OVERWRITE TRUE,
        ROW_GROUP_SIZE 122880,
        COMPRESSION SNAPPY
    );
    """

    print("Running final DuckDB COPY statement...")
    # 🛑 The DuckDB execute method handles running the multi-line SQL 🛑
    con.execute(copy_sql)
    print(f"🎉 SUCCESS: Tiled dataset generated by DuckDB native COPY to: {OUTPUT_TILED_GEOPARQUET_DIR}")

except Exception as e:
    print(f"❌ CRITICAL ERROR during generation: {e}")

finally:
    con.close()
    print("DuckDB connection closed.")
