# .github/workflows/deploy.yml
name: Deploy Vite App to GitHub Pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Update to the latest version
        with:
          node-version: "20" # Ensure compatibility with Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
        id: deployment
        uses: actions/deploy-pages@v4
